apiVersion: v1
kind: Pod
metadata:
  labels:
    build: gradle
    jenkins: agent
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:latest
  - name: gradle
    image: gradle:jdk8:latest
    command: ["cat"]
    tty: true
